set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)

set(TOOLCHAIN_ROOT $ENV{TOOLCHAIN})

set(CMAKE_C_COMPILER   ${TOOLCHAIN_ROOT}/bin/riscv64-unknown-linux-musl-gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_ROOT}/bin/riscv64-unknown-linux-musl-g++)

set(CMAKE_SYSROOT ${TOOLCHAIN_ROOT}/sysroot)

set(CMAKE_FIND_ROOT_PATH ${CMAKE_SYSROOT} ${TOOLCHAIN_ROOT})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
