// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#pragma once

#define HAS_ARRAY_BOUNDS
#define HAS_BITWISE_INSTEAD_OF_LOGICAL
#define HAS_CAST_FUNCTION_TYPE
/* #undef HAS_CATCH_VALUE */
/* #undef HAS_CLASS_MEMACCESS */
#define HAS_DEPRECATED_COPY
#define HAS_DEPRECATED_DECLARATIONS
#define HAS_DEPRECATED_LITERAL_OPERATOR
#define HAS_DEPRECATED_THIS_CAPTURE
#define HAS_FORMAT_TRUNCATION
#define HAS_IGNORED_ATTRIBUTES
/* #undef HAS_MAYBE_UNINITIALIZED */
#define HAS_MISSING_BRACES
/* #undef HAS_NONNULL_COMPARE */
#define HAS_PARENTHESES
#define HAS_REALLOCARRAY
#define HAS_SHORTEN_64_TO_32
#define HAS_TAUTOLOGICAL_POINTER_COMPARE
#define HAS_UNUSED_BUT_SET_PARAMETER
#define HAS_UNUSED_BUT_SET_VARIABLE
#define HAS_UNUSED_VARIABLE
/* #undef HAS_USELESS_CAST */
#define ORT_BUILD_INFO "ORT Build Info: git-branch=HEAD, git-commit-id=9bb02204b, build type=Release"
#define ORT_VERSION "1.24.2+spacemit.a1"
